name: run multiple jobs
on: push
jobs:
  develop_job:
    runs-on: ubuntu-latest
    steps:
      - name: install the cowsay
        run: sudo apt-get install cowsay -y
      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover , I am a DRAGON...RAWR">> dragon.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact
        with:
          name: dragon-text-file #to uplod the artifact
          path: dragon.txt
      - name: sleep for 30 seconds
        run: sleep 30
  test_job:
    needs: develop_job
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 10 seconds
        run: sleep 10
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      - name: test the files it is present or not
        run: grep -i "dragon" dragon.txt
  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      - name: Read the file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying 🙈
