name: secrets and values of yaml
on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Select the branch"
                required: true
                default: "staging"
                type: choice
                options:
                    - main
                    - QA
                    - feauture Branch
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: docker build
              run: echo "docker build -t docker.io/dockerusername/imagetag:latest"

            - name: docker login
              run: echo "docker login --username=dockerusername --password=dockerpassword
    docker_push:
        needs: docker_build
        runs-on: ubuntu-latest
        steps:
            - name: docker push
              run: echo "docker push docker.io/dockerusername/imagetag:latest"
