name: secrets and values of yaml
on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Select the branch"
                required: true
                default: "staging"
                type: choice
                options:
                    - main
                    - QA
                    - feauture Branch
jobs:
    docker_build:
        runs-on: ubuntu-latest
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: chandra005
            IMAGETAG: github-actions:nginx
            DOCKER_PASSWORD: Amma@0911

        steps:
            - name: docker information
              run: docker info
            - name: docker build
              run: docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_USERNAME}}:latest

            - name: docker login
              run: echo "docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}
    docker_push:
        needs: docker_build
        runs-on: ubuntu-latest
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: chandra005
            IMAGETAG: github-actions:nginx
            DOCKER_PASSWORD: Amma@0911
        steps:
            - name: docker push
              run: echo "docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGETAG}}:latest"
