name: secrets and values of yaml

on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Select the branch"
                required: true
                default: "staging"
                type: choice
                options:
                    - main
                    - QA
                    - feature Branch

jobs:
    docker_build:
        runs-on: ubuntu-latest
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: chandra005
            IMAGE_NAME: github-actions-nginx
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Show Docker info
              run: docker info

            - name: Build Docker image
              run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

            - name: Login to Docker Hub
              run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    docker_push:
        needs: docker_build
        runs-on: ubuntu-latest
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: chandra005
            IMAGE_NAME: github-actions-nginx
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        steps:
            - name: Login to Docker Hub
              run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

            - name: Push Docker image
              run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
