name: secrets and values of yaml

on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Select the branch"
                required: true
                default: "staging"
                type: choice
                options: [main, QA, "feature Branch"]

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: chandra005
            IMAGE_NAME: github-actions-nginx # no colon here
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Docker info
              run: docker info

            - name: Login to Docker Hub
              run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

            - name: Build image
              run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

            - name: Push image
              run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
